image: Previous Visual Studio 2019
version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test: off
artifacts:
- path: .\Babalouba\bin\Release\netcoreapp3.1\Babalouba.exe